# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4942fef65bef7e8cc9701db9f372fe8bdc0fbdec09f10aa1dd0e12da1f377ee0ca72adb90016430911620a77e200796373f08ddb6d48835fbc3d18e5c4ec15a0

test:
  secret_key_base: 542d985ad8bb8a766021ec7dcd648aa3c512a11a33bf3acf2fe74d9734631d51337d6154fb0cf28e0e553580f1eb23cdf93ac9e8595752c2ebf5baed44be7494

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
